# Generated by Django 3.1.3 on 2021-03-09 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Walks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.JSONField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.ManyToManyField(blank=True, related_name='profile', to='api.Review')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('walks', models.ManyToManyField(blank=True, related_name='profile', to='api.Walks')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('website', models.CharField(blank=True, default='', max_length=100)),
                ('lng', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=9)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('reviews', models.ManyToManyField(blank=True, related_name='business', to='api.Review')),
            ],
        ),
    ]
