# Generated by Django 3.1.3 on 2021-03-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walks',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='walks',
            old_name='longitude',
            new_name='lng',
        ),
    ]
