# Generated by Django 3.1.3 on 2021-03-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210307_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
    ]
