# Generated by Django 3.1.3 on 2021-03-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210303_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='business',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='walks',
            name='lat',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='walks',
            name='long',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
