# Generated by Django 3.1.3 on 2021-03-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210307_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='lat',
            field=models.DecimalField(decimal_places=25, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='business',
            name='lng',
            field=models.DecimalField(decimal_places=25, default=0.0, max_digits=30),
        ),
    ]
