# Generated by Django 3.1.3 on 2021-03-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210307_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
    ]
