# Generated by Django 3.1.3 on 2021-03-04 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210303_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='long',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='walks',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='walks',
            old_name='long',
            new_name='longitude',
        ),
    ]
