# Generated by Django 3.1.3 on 2021-03-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210303_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Walks',
        ),
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
