# Generated by Django 3.1.3 on 2021-03-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210307_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
