# Generated by Django 3.1.3 on 2021-03-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_walks'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
    ]
