# Generated by Django 3.1.3 on 2021-03-08 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20210306_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='business',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='walks',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='walks',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='walks',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='walks',
            name='longitude',
        ),
        migrations.AddField(
            model_name='business',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='business',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='walks',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='walks',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.ManyToManyField(blank=True, related_name='profile', to='api.Review')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('walks', models.ManyToManyField(blank=True, related_name='profile', to='api.Walks')),
            ],
        ),
    ]
