# Generated by Django 3.1.3 on 2021-03-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210306_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
