# Generated by Django 3.1.3 on 2021-03-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210307_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='rating',
            new_name='average_rating',
        ),
    ]
