# Generated by Django 3.1.3 on 2021-03-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210307_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='average_rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
